-include proxy.mk
# http_proxy = http://username:password@proxy:80/

all: bugs720x576x20.avi disney1920x1080x8.avi bugs720x576.avi

bugs720x576x20.avi:
	wget http://www.module.ru/mb7707/NeuroMatrix/sobel/$(@)
	
disney1920x1080x8.avi:
	wget http://www.module.ru/mb7707/NeuroMatrix/sobel/$(@)

bugs720x576.avi:
	wget http://www.module.ru/mb7707/NeuroMatrix/sobel/$(@)
